add ssd1306 library
RT-Thread/mpy-snippets pull request #54
Opened 2020-04-01 02:19 UTC by xupenghu

add ssd1306 library

2020-04-21 06:34 UTC, xupenghu commented
Is there something wrong with the pr?

2020-05-06 06:05 UTC, SummerGift requested changes

2020-05-06 06:05 UTC, SummerLife commented on library/ssd1306/ssd1306_example.py
> +
需要删除多余空行

2020-05-06 06:05 UTC, SummerLife commented on library/ssd1306/ssd1306.py
> +
这里有缺少末尾行提示

2020-05-06 06:05 UTC, SummerLife commented on library/ssd1306/font.py
> +];
需要添加新行

2020-05-06 06:08 UTC, SummerLife commented
抱歉，可能是我漏掉了提示邮件，review 已经在上面给出，感谢提交。

2020-05-06 06:31 UTC, xupenghu commented on library/ssd1306/ssd1306.py
> +
末尾行提示是什么意思？

2020-05-06 08:31 UTC, SummerLife commented on library/ssd1306/ssd1306.py
> +
在代码文件末尾，一般要求另起一行，是为了便于一些文本处理软件来处理，这里 github 提示末尾没有另起新行。

2020-05-06 08:32 UTC, SummerLife commented on library/ssd1306/ssd1306.py
> +
注意这个提示符：

![image](https://user-images.githubusercontent.com/22132180/81155065-24f45180-8fb7-11ea-8cea-bd50591e3eee.png)

2020-05-06 11:32 UTC, SummerGift approved these changes

2020-05-06 11:32 UTC, merged